name: Publish on Push && schedule

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "22 3 * * 0"
  workflow_dispatch:

env:
  BASE_DEVEL_IMG: base-devel
  LATEST_IMG: latest
  BASE_IMG: base

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: mikuxdev/archlinux-pkgbuild:latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set fastest mirrors
        run: |
          pacman -Syyu --noconfirm reflector
          reflector --age 6 --connection-timeout 15 --download-timeout 15 --latest 21 --fastest 21 --threads 21 --sort rate --protocol https --save /etc/pacman.d/mirrorlist

      - name: Install dependencies
        run: pacman -Syyu --noconfirm --needed make docker docker-buildx devtools fakeroot fakechroot

      - name: Build base
        run: |
          make archfiery-base
          docker tag mikuxdev/base docker.io/mikuxdev/archfiery$BASE_IMG:$LATEST_IMG

      - name: Build base-devel
        run: |
          make archfiery-base-devel
          docker tag mikuxdev/base-devel docker.io/mikuxdev/$BASE_DEVEL_IMG:$LATEST_IMG

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: |
          docker push docker.io/mikuxdev/$BASE_IMG:$LATEST_IMG
          docker push docker.io/mikuxdev/$BASE_DEVEL_IMG:$LATEST_IMG

